### ISSUE TITLE
Export schedule.json

### ISSUE THREAD

**Issue by ydubreuil** [breizhcamp/callForPaper#10]

**Comment by nbulteau** [comment]
Est-ce qu'on a une cible sur la structure attendue ?

**Comment by alexthomazo** [comment]
Oui, le format de sched.org, t'as un exemple dans la branche DockerCon de la likebox ici : https://github.com/breizhcamp/LikeBox/blob/dockercon/server/schedule.json

**Comment by nbulteau** [comment]
ok je pars la dessus
