### ISSUE TITLE
Mettre a jour les templates mails

### ISSUE THREAD

**Issue by alexthomazo** [breizhcamp/callForPaper#22]
"Brander" les templates mail aux couleurs du BreizhCamp (au moins mettre a jour liens, email de contact dans footer)
dans le répertoire `src/main/webapp/WEB-INF/classes`

- [x] Soumission d'un talk
- [x] Vérification de création de compte
- [x] Nouveau Message 
- [x] Nouveau Message Admin
- [x] Session non sélectionné
- [x] Session sélectionné
- [x] Session en liste d'attente (???)

**Comment by MarcAudefroy** [comment]
- [x] Soumission d'un talk
- [ ] Vérification de création de compte
- [ ] Nouveau Message 
- [ ] Nouveau Message Admin
- [ ] Session non sélectionné
- [ ] Session sélectionné
- [ ] Session en liste d'attente ? (Je ne comprends pas ce statut)

**Comment by MarcAudefroy** [comment]
La soumission d'un talk donne ce mail : 
<img width="961" alt="screen shot 2015-11-30 at 02 26 00" src="https://cloud.githubusercontent.com/assets/2056363/11461781/6a9fc07a-970a-11e5-8f3c-929fdbaf4950.png">

**Comment by jljouannic** [comment]
L'utilisateur ayant la possibilité de choisir la langue dans l'UI, dans l'idéal, prévoir des templates internationalisés. (Mais ça peut attendre).

**Comment by nbulteau** [comment]
@jljouannic pour l'information de la langue est coté front.
On pourrait aussi ajouter un attribut langue au niveau du profil.

**Comment by jljouannic** [comment]
À défaut d'avoir la langue dans le profil, il est toujours possible de récupérer la valeur du header `Accept-Language`côté serveur. Sa valeur correspond à la langue du navigateur (quand la requête est émise depuis un navigateur évidemment), donc normalement à la langue de l'utilisateur.

**Comment by nbulteau** [comment]
@jljouannic La plupart des envoies de mail ne sont pas issues d'une requête directe (sauf le mail de "confirmation de l'email" et le mail de "confirmation du dépôt d'une session"). 
On va avoir du mal a couper à l'attribut langue au niveau du profil.

Le mécanisme d'envoie de mail en Français ou en Anglais est en place, je dois finir de traduire les mails.
