### ISSUE TITLE
Page de confirmation de soumission de talk

### ISSUE THREAD

**Issue by alexthomazo** [breizhcamp/callForPaper#23]
Lorsque l'on valide un talk, on est redirigé vers la page de login au lieu de la page de confirmation du talk

**Comment by jljouannic** [comment]
Le fonctionnement n'est plus celui attendu. Après que l'utilisateur ait confirmé la soumission de sa proposition, il doit être redirigé vers la page lui indiquant que son talk a été soumis.

**Comment by MarcAudefroy** [comment]
Ouais mais c'est juste une page t'indiquant que le talk a été soumis...ce qui normalement est évident. C'est pas mieux de rediriger directement l'utilisateur sur le dashboard avec une notification? On peut rajouter dans le message de notification qu'un mail lui a été envoyé.

Mais si faut garder la page de confirmation, je la remet.

**Comment by ndeloof** [comment]
:+1: pour un message flash qui confirme la soumission et indique qu'un mail de confirmation a été envoyé
