### ISSUE TITLE
Erreur lors de la soumission d'un talk si pas de serveur mail.

### ISSUE THREAD

**Issue by MarcAudefroy** [breizhcamp/callForPaper#27]
Lors de la soumission d'un talk, une erreur est généré si il n'y a pas de serveur mail. L'utilisateur voit alors une alerte alors que son talk est bien enregistré en base.

3 scénarios possibles pour corriger:

- On laisse le talk enregistré et on ne prévient pas l'utilisateur. Affichage d''un message vert de succès côté client.
- On laisse le talk enregistré et on prévient l'utilisateur de l'échec d'envoi de mail. Affichage d''un message orange de ce problème côté client.
- Faire un rollback sur la soumission en cas d'erreur d'envoi mail et affiché un message rouge d'erreur côté client en rouge.

**Comment by MarcAudefroy** [comment]
Si on choisit la deuxième solution. On met quoi comme erreur HTTP? 418? :D

**Comment by ndeloof** [comment]
on met en succès, et on logge une alerte serveur
c'est pas vraiment un cas nominal, donc on va considérer qu'on est pas sensé le gérer dans le code
dans un monde merveilleux on mettrait ça dans une file pour post-traitement...
