### ISSUE TITLE
Saisir les informations du profil avant de pouvoir saisir un talk

### ISSUE THREAD

**Issue by jljouannic** [breizhcamp/callForPaper#28]

**Comment by MarcAudefroy** [comment]
Et ça se matérialiserais comment? Le bouton d'ajout de talk grisé avec un message invitant à compléter son profil?

**Comment by jljouannic** [comment]
Ouais, un truc dans le genre. Je vais essayer de m'y mettre durant la pause déjeuner aujourd'hui tout en refaisant le layout des vues de zéro pour repartir de quelque chose de propre pour la suite.
