### ISSUE TITLE
Gestion de la config OAuth2, ReCaptcha côté client à revoir

### ISSUE THREAD

**Issue by jljouannic** [breizhcamp/callForPaper#30]
Pour le moment, le fichier `app.js` contient cette configuration «en dur» :
```
…
.constant('Config', {
    'recaptcha': 'yourRecaptchaPublicToken',
    'googleClientId': 'yourGoogleClientId',
    'githubClientId': 'yourGithubClientId'
  })
…
```
Ces éléments sont connus du serveur (fichier application.properties).

Ajouter une ressource REST en accès libre pour que le code client récupère ces éléments durant le chargement de l'application dans le navigateur ?

**Comment by ndeloof** [comment]
on peut rendre `app.js` dynamique (généré par le serveur) pour qu'il injecte ce genre d'infos en sync avec la conf backend.

**Comment by jljouannic** [comment]
Bof… Je préfères conserver l'API REST comme unique lien entre le client et le serveur. Plus simple à mettre en œuvre. Plus simple à maintenir.

**Comment by ndeloof** [comment]
ça me va, ça crée un asynchronisme que j'ai tendance à éviter, mais bon ce sont mes restes de GWT qui parlent là - sur cette techno, c'était un pattern d'inclure dans la page hôte les données initiales calculées côté serveur.

**Comment by jljouannic** [comment]
Voir 75cd347ebdcea329fee9c41d8d5db7e9f618ee27 pour l'implémentation côté backend.
