### ISSUE TITLE
Consultation des talks soumis à revoir

### ISSUE THREAD

**Issue by jljouannic** [breizhcamp/callForPaper#33]
Il s'agit de l'écran permettant à l'utilisateur de consulter les talks qu'il a soumis.

* Ne conserver que les onglets `Talk` et `Contact`.
* Le contenu de l'onglet `Talk` est à vérifier.

**Comment by MarcAudefroy** [comment]
l'onglet speaker peut être intéressant pour nous et pour le cas des co-speakers.

**Comment by MarcAudefroy** [comment]
Les cospeakers ne sont pas affiché

**Comment by MarcAudefroy** [comment]
Le talk pour un cospeaker n'est pas chargé.
