### ISSUE TITLE
authentification Google KO

### ISSUE THREAD

**Issue by ndeloof** [breizhcamp/callForPaper#37]
La première fois j'ai eu :
'The redirect URI in the request: https://cfp.breizhcamp.org did not match a registered redirect URI.'

Et maintenant :
"désolé, il y a eu une erreur avec le serveur distant"

(au passage, ça existe un serveur "local" ? :P)

**Comment by ydubreuil** [comment]
Corrigé en activant l'API G+

**Comment by ndeloof** [comment]
"Il existe déjà un utilisateur associé à ce fournisseur"
?

**Comment by ndeloof** [comment]
a priori, conflit avec un compte créé via github. 
ce qui ne devrait pas être le cas: le user doit être identifié par son email
NB: un compte github n'a pas forcément d'email enregistré, dans ce cas il faut refuser l'authent, si possible avec un message d'explication

**Comment by ydubreuil** [comment]
Je propose de continuer la discussion dans #39
