### ISSUE TITLE
authentification multiprovider KO

### ISSUE THREAD

**Issue by ydubreuil** [breizhcamp/callForPaper#39]
Après voir créé son compte avec l'intégration Google, impossible de se connecter avec Github, on a ce message : "Il existe déjà un utilisateur associé à ce fournisseur"

**Comment by ndeloof** [comment]
pareil dans l'autre sens. Est-ce que c'est bien l'email (seul) qui est utilisé comme clé ?
NB: un compte github peut ne pas avoir d'email renseigné, dans ce cas prévoir un zoli message d'erreur

**Comment by jljouannic** [comment]
C'est quoi le comportement attendu ? Un utilisateur ayant créé son compte au travers d'une authentification Google devrait pouvoir, par la suite, s'authentifier avec Github s'il le souhaite ? Voir même au travers de l'autentification par email ?

**Comment by ndeloof** [comment]
oui exactement. Le fournisseur OAuth ne doit permettre que de valider l'identité (i.e. l'email) et éventuellement pré-remplir le profil utilisateur

**Comment by nbulteau** [comment]
@ndeloof si il y a un conflit d'email on fait quoi ? 
L'email Github et l'email Google ne sont pas les même : je conserve le premier email récupéré OK avec ça ?

**Comment by ndeloof** [comment]
@nbulteau je pige pas ta question: s'il ya a des emails !=, tu te retrouve avec deux utilisateurs, sans liens entre les profils.

**Comment by nbulteau** [comment]
@ndeloof : Ok t'as raison ça n'a pas de sens
Donc un scénario du type :
1 - Je me connecte pour la première fois avec Google (mon profil est donc renseigné)
2 - Je me déconnecte 
3 - Je me connecte a nouveau, mais cette fois ci avec Github (et mon email n'est pas le même que pour mon google)

Donne deux utilisateurs, sans liens entre les profils...

**Comment by ndeloof** [comment]
dans une v2 on prevoira peut être une fonction de "merge" entre utilisateurs, pour ceux qui ont ce genre de setup avec un email différent par service (genre Nico Ledez), mais c'est priorité super basse.
