### ISSUE TITLE
La suppression d'un talk, depuis l'admin, ne fonctionne pas

### ISSUE THREAD

**Issue by jljouannic** [breizhcamp/callForPaper#52]
Constaté en essayant de supprimer les talks «tests» [2](https://cfp.breizhcamp.org/#/admin/sessions/2) et [3](https://cfp.breizhcamp.org/#/admin/sessions/3)

**Comment by nbulteau** [comment]
@jljouannic je ne reproduit pas en local.

![image](https://cloud.githubusercontent.com/assets/1934133/11791739/b9c8a196-a2a2-11e5-863c-c0ae7fd49ca7.png)

**Comment by nbulteau** [comment]
@jljouannic Comment peut-on avancer sur cette issue ?
Je ne suis pas admin sur la prod et je ne reproduit pas en local.
Peux tu me donner plus d'infos :
- La séquence des URLs envoyées vers le back.
- Un extrait des logs produits.

**Comment by jljouannic** [comment]
Après examen rapide, tenter du supprimer les talks [2](https://cfp.breizhcamp.org/#/admin/sessions/2) et [3](https://cfp.breizhcamp.org/#/admin/sessions/3) génère la réponse suivante du serveur :

```json
{
	"timestamp": 1450254831726,
	"status": 500,
	"error": "Internal Server Error",
	"exception": "class org.springframework.dao.DataIntegrityViolationException",
	"message": "org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}
```

En revanche, je ne suis pas parvenu à reproduire le problème en créant puis supprimant un talk par moi-même.

Peut-être que les talks problématiques ont été saisis à un moment ou l'application n'était pas encore très stable.

Je propose de les supprimer manuellement.

**Comment by nbulteau** [comment]
Je propose qu'on 'close' cette issue
