### ISSUE TITLE
Mettre en avant les durées et catégories pour un talk

### ISSUE THREAD

**Issue by nono** [breizhcamp/callForPaper#62]
Salut,

si, comme moi, on arrive sur le site du cfp sans avoir une idée très précise de quel talk proposer, on est bien embêté. Ce n'est pas facile de trouver les durées et catégories : 

- il faut créer un compte
- remplir sa bio
- puis aller sur le formulaire de création d'un talk

Je pense que ces quelques infos (ou un paragraphe d'explication) pourrait être mise en ligne sur la page d'accueil non-connecté.

Ha, sinon, ça devrait être Langages et non Lang_u_ages dans les catégories, non ?

**Comment by jljouannic** [comment]
Merci de nous signaler ce qui cloche. J'espère que ces quelques désagréments ne t'ont pas empêché de soumettre une ou plusieurs propositions. On va essayer d'apporter les corrections nécessaires.

**Comment by MarcAudefroy** [comment]
Je fais ça ce soir. :)
