### ISSUE TITLE
Co-speaker

### ISSUE THREAD

**Issue by ydubreuil** [breizhcamp/callForPaper#7]

**Comment by MarcAudefroy** [comment]
Concernant cette fonctionnalité :

Est-ce qu'un co-speaker doit pouvoir voir le talk dans sa propre liste? Peut-il l'éditer?
Si c'est le cas, ça implique une relation ManyToMany entre la table Talks et Users et non OneToMany.

**Comment by MarcAudefroy** [comment]
Dans un premier temps, je ferais juste une liste de co-speakers toute simple. Ces derniers ne le verront donc pas dans leur dashboard.

**Comment by ndeloof** [comment]
ok pour fonctionner en l'état dans un premier temps. 
ce serait bien que le co-speaker ait au moins une indication des talks auxquels il participe (une liste à part dans le dashboard ?). Pour l'édition par contre il me semble mieux que seul le speaker principal ait accès.
