### ISSUE TITLE
introduire un /healthCheck

### ISSUE THREAD

**Issue by ndeloof** [breizhcamp/callForPaper#95]

**Comment by ydubreuil** [comment]
c'est déjà dispo avec Spring Boot et déjà exposé si je ne m'abuse

**Comment by alexthomazo** [comment]
il faudra effectivement activer la feature intégrée de Spring boot : http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-health

**Comment by nbulteau** [comment]
implémenté avec actuator : /health 

On désactive en prod le reste :+1: endpoints.autoconfig.enabled=false
endpoints.beans.enabled=false
endpoints.configprops.enabled=false
endpoints.dump.enabled=false
endpoints.env.enabled=false
endpoints.info.enabled=false
endpoints.liquibase.enabled=false
endpoints.metrics.enabled=false
endpoints.mappings.enabled=false
endpoints.shutdown.enabled=false
endpoints.trace.enabled=false

**Comment by nbulteau** [comment]
En fait on disable tout sauf /health

# disable everything except health
endpoints.enabled=false
endpoints.health.enabled=true
